### PR TITLE
Bump TargetRubyVersion in rubocop configs to 2.5 (#54)

### LINKED ISSUE #54: Ruby version 2.4 is unsupported from rubocop 1.12
Running `rubocop` on a new Ruby project would yield:

```
Running RuboCop...
Error: RuboCop found unsupported Ruby version 2.4 in `TargetRubyVersion` parameter (in .rubocop-https---raw-githubusercontent-com-riboseinc-oss-guides-master-ci-rubocop-yml). 2.4-compatible analysis was dropped after version 1.12.
Supported versions: 2.5, 2.6, 2.7, 3.0, 3.1
RuboCop failed!
```

Is the correct fix to bump the `TargetRubyVersion` to something like `2.7`?

### PR DESCRIPTION
**Pull request by ribose-jeffreylau**
closes #54

### CODE REVIEW

**Comment by opoudjis** [comment]
This is still pending

**Comment by ronaldtse** [comment]
We probably should bump this to 3.0?

**Comment by ribose-jeffreylau** [comment]
Bumping to 3.1 instead, as 3.0.6 will be EOL soon, according to ruby lang's official site:

Screenshot 2023-11-06 at 15 33 31

**Review by ronaldtse — APPROVED** [review]

**Comment by ronaldtse** [comment]
Thanks guys!

**Pull request merged**
